### ISSUE TITLE
Auto-open correct download for user without dependencies 

### ISSUE THREAD

**Issue by AdamRolek500** [ajchili/sync#108]
if a user does not the correct version of vlc or java, take them to the download page for the programs respectively.

**Comment by ajchili** [comment]
@AdamRolek500 We should instead make an auto-downloaded. It would download the correct dependencies automatically then open them for the user to install. However, we would have to ensure that we notify a user that they may already have an incorrect version installed (the incorrect version would have to be uninstalled).
