### ISSUE TITLE
Integrate Netflix and Crunchyroll through a Chrome extension

### ISSUE THREAD

**Issue by ajchili** [ajchili/sync#61]
- [ ] Implement way to load into show and sync with other users
  - [ ] Detect when show is loaded
- [ ] Implement auto pause/play for buffering users
- [ ] Implement chat feature

**Comment by saberchicken** [comment]
+1 for anime

**Comment by ajchili** [comment]
If you want, you can look into how to setup a Java web browser. If you do, just post what you believe to be relevant here.

**Comment by ajchili** [comment]
http://htmlunit.sourceforge.net/
https://www.teamdev.com/jxbrowser

**Comment by ajchili** [comment]
After testing both htmlunit and jxbrowser, neither will work. Another solution needs to be found.

**Comment by ajchili** [comment]
[cdp4j](https://github.com/webfolderio/cdp4j) may be our solution.

**Comment by ajchili** [comment]
cdp4j seems to not have audio, if we can get around this then we may be golden.

**Comment by ajchili** [comment]
cdp4j won't be used, [SeleniumHQ](https://github.com/SeleniumHQ/selenium) will be used instead.

**Comment by ajchili** [comment]
To track progress for Netflix/Crunchyroll, follow [this](https://github.com/ajchili/sync/tree/selenium) branch.

**Comment by ajchili** [comment]
Having issues with Netflix as my account is being locked out, however, some progress can be made with Crunchyroll with [swfobject](https://github.com/swfobject/swfobject).

**Comment by ajchili** [comment]
This will become a chrome plugin

**Comment by ajchili** [comment]
Creating new issue that is not as cluttered.
