### ISSUE TITLE
Add preview in timeline

### ISSUE THREAD

**Issue by elijahcutler** [ajchili/sync#90]
Make it possible to see desired time before skipping to actual mark on the timeline.
![dqmb0k8brfwb8diggbqp7g](https://user-images.githubusercontent.com/16292040/34551302-85ef1870-f0e6-11e7-8523-9e6455949d0a.png)

**Comment by ajchili** [comment]
@elijahcutler look at [this](http://ronallo.com/blog/a-plugin-for-mediaelement-js-for-preview-thumbnails-on-hover-over-the-time-rail/) for implementation ideas.

**Comment by elijahcutler** [comment]
[For future reference](https://www.npmjs.com/package/videojs-thumbnails)

**Comment by elijahcutler** [comment]
Not possible with current implementation.
