### ISSUE TITLE
Modifying audio track and using subtitles from .mkv files

### ISSUE THREAD

**Issue by Lophis** [ajchili/sync#94]
Using an mkv file, with multiple audio tracks and subtitle files included in the video file, it is currently impossible to right click and modify said settings as we can do it in VLC, it would be cool if that was available.

**Comment by ajchili** [comment]
[This](http://capricasoftware.co.uk/#/projects/vlcj/tutorial/media-info) will be helpful when implementing this feature.

**Comment by ajchili** [comment]
This may not be possible with the new platform (Java -> Electron), but this will still be investigated.
